2025-03-21 13:33:35,610 ERROR: Exception on /users [GET] [in /home/student/DBWE/myenv/lib/python3.9/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/student/DBWE/app/routes.py", line 153, in user_list
    return render_template('user_list.html', title='Users', users=users)
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask/templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask/templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: user_list.html
