2025-03-21 13:31:00,775 ERROR: Exception on /users [GET] [in /home/student/DBWE/myenv/lib/python3.9/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/student/DBWE/app/routes.py", line 153, in user_list
    return render_template('user_list.html', title='Users', users=users)
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/student/DBWE/app/templates/user_list.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "/home/student/DBWE/app/templates/base.html", line 2, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block 'body'
    {% block content -%}
  File "/home/student/DBWE/app/templates/base.html", line 49, in block 'content'
    {% block app_content %}{% endblock %}
  File "/home/student/DBWE/app/templates/user_list.html", line 13, in block 'app_content'
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2025-03-21 13:31:05,546 ERROR: Exception on /users [GET] [in /home/student/DBWE/myenv/lib/python3.9/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/student/DBWE/app/routes.py", line 153, in user_list
    return render_template('user_list.html', title='Users', users=users)
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/student/DBWE/app/templates/user_list.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "/home/student/DBWE/app/templates/base.html", line 2, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block 'body'
    {% block content -%}
  File "/home/student/DBWE/app/templates/base.html", line 49, in block 'content'
    {% block app_content %}{% endblock %}
  File "/home/student/DBWE/app/templates/user_list.html", line 13, in block 'app_content'
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2025-03-21 13:31:41,994 ERROR: Exception on /users [GET] [in /home/student/DBWE/myenv/lib/python3.9/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/student/DBWE/app/routes.py", line 153, in user_list
    return render_template('user_list.html', title='Users', users=users)
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/student/DBWE/app/templates/user_list.html", line 2, in top-level template code
  File "/home/student/DBWE/app/templates/base.html", line 2, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block 'body'
    {% block content -%}
  File "/home/student/DBWE/app/templates/base.html", line 49, in block 'content'
    {% block app_content %}{% endblock %}
  File "/home/student/DBWE/app/templates/user_list.html", line 13, in block 'app_content'
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
