2025-03-21 14:11:10,377 ERROR: Exception on /user/nico [GET] [in /home/student/DBWE/myenv/lib/python3.9/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/student/DBWE/app/routes.py", line 82, in user
    return render_template('user.html', user=user, posts=posts.items, next_url=next_url, prev_url=prev_url, form=form)
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
  File "/home/student/DBWE/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/student/DBWE/app/templates/user.html", line 15, in template
    {% endif %]
jinja2.exceptions.TemplateSyntaxError: expected token 'end of statement block', got '%'
2025-03-21 14:24:43,818 INFO: Microblog startup [in /home/student/DBWE/app/__init__.py:29]
2025-03-21 14:24:43,942 INFO: Microblog startup [in /home/student/DBWE/app/__init__.py:29]
2025-03-21 14:24:43,966 INFO: Microblog startup [in /home/student/DBWE/app/__init__.py:29]
2025-03-21 14:24:43,997 INFO: Microblog startup [in /home/student/DBWE/app/__init__.py:29]
2025-03-21 14:27:35,838 INFO: Microblog startup [in /home/student/DBWE/app/__init__.py:29]
2025-03-21 14:27:36,080 INFO: Microblog startup [in /home/student/DBWE/app/__init__.py:29]
2025-03-21 14:27:36,115 INFO: Microblog startup [in /home/student/DBWE/app/__init__.py:29]
2025-03-21 14:27:36,176 INFO: Microblog startup [in /home/student/DBWE/app/__init__.py:29]
2025-03-21 14:49:40,882 INFO: Microblog startup [in /home/student/DBWE/app/__init__.py:29]
